# Generated by Django 2.2.4 on 2019-10-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=32, verbose_name='博文标题')),
                ('blog_detail', models.TextField(verbose_name='博文详情')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('blog_photo', models.TextField(verbose_name='博文图片')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '博客详情表',
                'verbose_name_plural': '博客详情表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, verbose_name='用户名')),
                ('user_email', models.TextField(verbose_name='用户邮箱')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('comment_date', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Blog', verbose_name='Blog外键')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User', verbose_name='User外键')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User', verbose_name='User外键'),
        ),
    ]
